### ISSUE TITLE
Electricity amount: Change dollar sign to rupee sign

### ISSUE THREAD

**Issue by cyberparam** [gsn2121/Tenant-Manager#3]
![Screenshot_2020-12-30-23-28-05-838_x1Trackmaster x1Trackmaster](https://user-images.githubusercontent.com/4871010/103371940-b68c7280-4af6-11eb-94b1-a86b551f9dc6.jpg)

**Comment by cyberparam** [comment]
@gsn2121 please change sign to rupees icon as successfully changed in other places. Close this and other issues if they are fixed. Ignore if fixed.

**Comment by gsn2121** [comment]
![image](https://user-images.githubusercontent.com/40537508/103375205-93b28c00-4aff-11eb-9fee-8ea2e0c421b8.png)

**Comment by cyberparam** [comment]
Ok
